### ISSUE TITLE
Proposiciones logicas

### ISSUE THREAD

**Issue by Yesus-12** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Yesus-12#3]
[Jesus.Sprint3.docx](https://github.com/user-attachments/files/17484281/Jesus.Sprint3.docx)

**Comment by AlynGomez12** [comment]
Portada:25/25
Procedimiento:22/25
Figuras, Ilustraciones y Fotografías:22/25
Resultados y conclusiones:22/25
Total:90/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
